### ISSUE TITLE
Enable forces for Sigma.7

### ISSUE THREAD

**Issue by ricmua** [ricmua/ros_force_dimension#10]
The delta robot has a control unit with a physical button  (see [page 16] of the manual). For the sigma robot, however, forces are enabled and disabled programmatically (see [page 20] of the manual). Examples in the [Force Dimension] SDK tend to invoke [`dhdEnableForce`] early in execution. This was likely true in early versions of the ROS2 node in this package, but the functionality was removed. In order to ensure that the node works with the sigma robot, this should be re-added. 

[page 16]: https://downloads.forcedimension.com/sdk/doc/fdsdk-3.14.0/user%20manual%20-%20delta.x.pdf#page=16

[page 20]: https://downloads.forcedimension.com/sdk/doc/fdsdk-3.14.0/user%20manual%20-%20sigma.7.pdf#page=20

[Force Dimension]: https://github.com/ricmua/ros_force_dimension/blob/main/doc/markdown/force_dimension.md

[`dhdEnableForce`]: https://downloads.forcedimension.com/sdk/doc/fdsdk-3.14.0/dhd/dhdc_8h.html#a178cf9ffa46dfe3d25dda74ecb34da31

**Comment by ricmua** [comment]
@Jshulgach : Could you test this with the Sigma.7?

I'm realizing that a test doesn't exist for this, so I'm going to work on a simple example script for forces.

**Comment by ricmua** [comment]
Although there is a [Python example] for quickly testing out the Force Dimension node, it does not involve forces. It would make sense to create another script that involves forces -- perhaps by mirroring the `center.cpp` example in the Force Dimension SDK.

[Python example]: https://github.com/ricmua/ros_force_dimension/blob/ricmua/enable_forces/main/doc/markdown/python_client_example.md

**Comment by Jshulgach** [comment]
Rebuilt the package with the new branch containing the `enable_forces` parameter on the Sigma.7. 

Confirmed the force feedback can now be enabled/disabled from updating the parameter just from running the included `force_dimension` package node!
